[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "isaacsim-examples"
version = "0.1.0"
description = "Telekinesis simulator for robot."
readme = "README.md"
requires-python = ">=3.11,<3.13"

authors = [
  { name = "Telekinesis", email = "support@telekinesis.ai" }
]

dependencies = [
    "loguru",
    "torch==2.7.0",
    "torchvision==0.22.0",
    "torchaudio==2.7.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://telekinesis.ai"
Documentation = "https://docs.telekinesis.ai"
